# 주제 : 성별에 따른 문화예술 참여율과 삶의 만족도 간의 상관관계



**데이터 관찰**

---

In [ ]:
#한국어 폰트 설치
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [ ]:
#필요한 라이브러리 임포트
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#한국어 폰트 설정 / 한국어 마이너스 설정
plt.rcParams['axes.unicode_minus'] = False
plt.rc('font', family='NanumGothic')

#시각화 스타일 설정
sns.set_palette("husl")

In [ ]:
#데이터셋 불러오기1

#문화예술_및_스포츠관람현황_시도 데이터
file_path1 = '/content/문화예술_및_스포츠관람현황_시도__20250420202622.xlsx'
culture_data = pd.read_excel(file_path1)

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
#데이터셋 불러오기2

#삶의_만족도_시도 데이터
file_path2 = '/content/삶의_만족도_시도__20250420202702.xlsx'
life_data = pd.read_excel(file_path2)

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
culture_data

,행정구역별(1),특성별(1),특성별(2),2011,2011.1,2011.2,2011.3,2011.4,2011.5,2011.6,...,2023.11,2023.12,2023.13,2023.14,2023.15,2023.16,2023.17,2023.18,2023.19,2023.20
0,행정구역별(1),특성별(1),특성별(2),계 (%),관람함 (%),관람횟수(평균) (회),- 음악·연주회·콘서트 (%),· 관람 횟수(평균) (회),- 연극·마당극·뮤지컬 (%),· 관람 횟수(평균) (회),...,- 박물관 (%),· 관람 횟수(평균) (회),- 미술관 (%),· 관람 횟수(평균) (회),- 문학행사 (회),· 관람 횟수(평균) (%),- 스포츠 경기 (%),· 관람 횟수(평균) (회),- 기타 (%),· 관람 횟수(평균) (회)
1,전국,전체,계,100,58.6,8.4,25.2,2.5,25,2.3,...,25.1,2.4,23.2,2.3,8.1,2,27.3,4.4,0.6,4.8
2,NaN,성별,남자,100,58,8.2,21.4,2.5,19.6,2.1,...,22,2.4,17.1,2.2,6.4,2.1,37.3,4.7,0.6,6.1
3,NaN,NaN,여자,100,59.2,8.7,28.7,2.6,30.2,2.4,...,28.1,2.4,29,2.4,9.6,2,17.9,3.7,0.5,3.2
4,서울특별시,전체,계,100,67,9.7,29.8,2.6,34.9,2.5,...,27.8,2.7,28.1,2.5,7.7,1.9,25.9,4.4,0.2,4.5
5,NaN,성별,남자,100,65.7,9.3,25.3,2.6,27.3,2.3,...,24.6,2.5,19,2.3,5.8,2,35.9,5,0.2,6.4
6,NaN,NaN,여자,100,68.3,10,33.9,2.6,41.9,2.7,...,30.5,2.9,35.9,2.7,9.3,1.9,17.4,3.2,0.3,3.4
7,부산광역시,전체,계,100,56.3,8.8,21.3,2.9,19.7,2.3,...,21.4,2.4,20.2,2.6,7.4,2.1,26.7,4.5,0.3,1
8,NaN,성별,남자,100,55.3,9,18.9,3,16.5,2.2,...,17.7,2.8,13.9,3.2,5.7,2,37,5.2,-,-
9,NaN,NaN,여자,100,57.3,8.6,23.4,2.8,22.7,2.4,...,24.8,2.2,26.1,2.3,9,2.2,17,3.1,0.5,1
10,대구광역시,전체,계,100,56.3,8.1,23.1,2.5,22.5,2,...,25.4,2.4,26.3,2.3,8.6,2,27.5,5.1,0.6,2.6
11,NaN,성별,남자,100,53.9,7.9,19.7,2.4,17,1.9,...,22.4,2.5,19.9,2.6,8.7,2.1,34.7,5.4,0.7,1.4
12,NaN,NaN,여자,100,58.6,8.4,26.1,2.5,27.4,2.1,...,28,2.3,31.9,2.2,8.5,2,21.4,4.6,0.6,3.9
13,인천광역시,전체,계,100,60,8.6,21.5,2.1,22.7,2.1,...,19.9,2.6,17.2,2.4,7.3,2.2,28.8,4.3,0.8,6.8
14,NaN,성별,남자,100,59.3,8.2,17.8,2,16.4,2,...,17.1,2.7,12.9,2.2,5.2,1.9,39.1,4.5,0.5,19.2
15,NaN,NaN,여자,100,60.7,8.9,25.1,2.2,28.7,2.2,...,22.6,2.6,21.4,2.6,9.4,2.4,18.6,3.9,1.2,2.0
16,광주광역시,전체,계,100,61.4,7.9,19.8,2.4,17.9,2.1,...,23.5,2.3,20.5,2.6,9.7,1.6,30.7,3.3,0.6,2.0
17,NaN,성별,남자,100,62.5,7.8,15.7,2.6,12.7,1.8,...,20.1,2.5,15.8,2.7,8.5,1.7,41.5,3.7,0.9,2.3
18,NaN,NaN,여자,100,60.4,8.1,23.8,2.3,23.1,2.2,...,26.8,2.1,25.1,2.6,10.9,1.5,20,2.6,0.3,1
19,대전광역시,전체,계,100,61.5,8.6,30.1,2.1,21.2,2.1,...,23.4,2.9,22.6,2,8,2.2,32,4.3,1.0,2.8
20,NaN,성별,남자,100,60.6,8.7,26.8,2.1,17,2.1,...,21.2,2.8,16.9,1.8,7.2,2.3,44.7,4.7,1.5,3.1
21,NaN,NaN,여자,100,62.3,8.5,33.2,2.2,25.3,2.1,...,25.6,3,28.5,2.1,8.9,2.2,18.6,3.3,0.6,2
22,울산광역시,전체,계,100,60.3,7,23.1,2.4,19.9,2.1,...,23.8,2.2,25.6,1.8,7.7,2.1,29.5,4.7,0.4,3.2
23,NaN,성별,남자,100,58.5,6.5,18.7,2.3,13.5,2.3,...,20.8,2.2,20.1,1.6,6.1,2,40.8,5.2,0.6,3.8
24,NaN,NaN,여자,100,62.2,7.5,27.3,2.5,26.2,2.1,...,26.9,2.2,31,1.9,9.2,2.2,18.5,3.5,0.2,1
25,세종특별자치시,전체,계,-,-,-,-,-,-,-,...,32.9,2.6,27.3,2.2,9.2,2.5,27.7,4.3,0.9,2.0
26,NaN,성별,남자,-,-,-,-,-,-,-,...,30,2.8,20.6,2,6.9,2.4,39.3,4.8,0.9,2.2
27,NaN,NaN,여자,-,-,-,-,-,-,-,...,35.6,2.4,33.4,2.3,11.4,2.6,16.9,3.4,0.9,1.8
28,경기도,전체,계,100,63.6,8.5,23.5,2.7,26.4,2.4,...,24.8,2.2,23.7,2.3,8.4,2,27.5,4.5,0.8,7.7
29,NaN,성별,남자,100,62.5,8.1,20.7,2.5,21.1,2.1,...,21.3,2.2,17.6,2.2,6.1,2.3,36.9,4.6,1.0,8.7
30,NaN,NaN,여자,100,64.7,8.8,26.2,2.8,31.5,2.7,...,28.1,2.2,29.6,2.3,10.7,1.8,18.5,4.2,0.5,5.9
31,강원특별자치도,전체,계,100,46.2,7.2,29.2,2.2,24.1,2,...,23.6,2,20.2,2.2,9.8,2.4,25.5,4.7,0.6,2.1
32,NaN,성별,남자,100,45.9,7.3,25.6,2.1,21.9,2.1,...,20.8,2.2,15,1.9,7.5,2.3,34.5,4.9,0.9,1.8
33,NaN,NaN,여자,100,46.6,7,32.6,2.3,26.2,2,...,26.1,1.9,25,2.3,11.9,2.5,17.2,4.3,0.4,3.0
34,충청북도,전체,계,100,47.7,7,20.4,2.3,16,2,...,27.5,2.1,23.5,1.9,9.1,2.1,20.9,4,1.0,2.6
35,NaN,성별,남자,100,45.4,7.1,18.4,2.4,13.3,1.9,...,24.2,2,20.1,1.6,7.8,1.8,31.8,3.9,1.3,3.3
36,NaN,NaN,여자,100,50,6.9,22.1,2.2,18.5,2,...,30.7,2.2,26.8,2.1,10.4,2.3,10.4,4.3,0.7,1.3
37,충청남도,전체,계,100,45.8,7.3,28.3,2.1,22.8,1.9,...,22.1,2.2,18,1.9,6.7,2.3,26.1,4.2,0.5,2.0
38,NaN,성별,남자,100,47.3,7,25.6,2.2,19.8,2,...,21.1,2.2,13.7,1.7,5.8,1.6,36.7,4.3,0.9,2.2
39,NaN,NaN,여자,100,44.4,7.6,31.2,2.1,26,1.8,...,23.1,2.2,22.6,2,7.7,2.8,14.8,3.8,0.1,1
40,전북특별자치도,전체,계,100,49.7,7.2,26.5,2.4,15.3,2,...,31.3,2.5,24,2.3,9.6,2.7,28.7,4.7,0.5,2.8
41,NaN,성별,남자,100,49.6,7.2,22.8,2.2,11.4,2.2,...,27.8,2.6,21.4,2.4,8.3,2.3,38.6,5.3,0.8,3.2
42,NaN,NaN,여자,100,49.8,7.2,30,2.6,19,2,...,34.6,2.4,26.4,2.2,10.8,3,19.3,3.6,0.2,1
43,전라남도,전체,계,100,46.5,6.7,31.5,2.4,19.1,2,...,26.6,2.4,23.2,2.4,9.9,2,31,3.9,0.4,1
44,NaN,성별,남자,100,50.7,6.7,27.1,2.4,13,1.8,...,24.3,2.4,16.7,2.7,8.5,2,40.3,4.3,0.4,1
45,NaN,NaN,여자,100,42.5,6.7,36.4,2.4,25.8,2.1,...,28.9,2.4,29.5,2.3,11.3,2.1,22,3.2,0.4,1
46,경상북도,전체,계,100,49.3,6.7,22.6,2.1,19.9,2.1,...,24.7,2.4,16.7,1.8,8,1.9,26.2,4.1,0.4,1.4
47,NaN,성별,남자,100,50.6,6.6,18.3,2,15.5,2.1,...,23.2,2.7,14.4,1.8,7.3,1.9,34.5,4.6,0.3,1.4
48,NaN,NaN,여자,100,48.1,6.8,27.1,2.2,24.5,2.1,...,26.3,2.1,19.2,1.8,8.8,1.8,17.2,3.1,0.5,1.5
49,경상남도,전체,계,100,51.5,8.1,20.4,2.9,14.3,2.1,...,25.7,2.3,20.3,2.1,6.2,2.1,27.2,4.3,0.5,1.6
50,NaN,성별,남자,100,52.2,7.6,14.1,3,11.3,2.2,...,22,2.4,16,2.1,5.2,2.4,38.6,4.7,0.5,1.6
51,NaN,NaN,여자,100,50.7,8.6,26.9,2.9,17.4,2.1,...,29.4,2.2,24.6,2,7.2,1.9,15.7,3.5,0.5,1.6
52,제주특별자치도,전체,계,100,51,8.2,27.9,2.9,19.7,2,...,24.2,2.3,22.5,2.3,7.4,1.8,33,5.6,0.6,1.9
53,NaN,성별,남자,100,49.1,8.5,21.4,3.4,13.7,2.2,...,20.4,2.5,16.7,2.2,6.8,1.8,44,6.3,0.2,5
54,NaN,NaN,여자,100,52.8,8,33.8,2.6,25,1.8,...,27.8,2.1,28,2.3,7.9,1.8,22.5,4.3,1.0,1.4

In [ ]:
life_data

,행정구역별(1),특성별(1),특성별(2),2011,2011.1,2011.2,2011.3,2011.4,2011.5,2013,...,2021.2,2021.3,2021.4,2021.5,2023,2023.1,2023.2,2023.3,2023.4,2023.5
0,행정구역별(1),특성별(1),특성별(2),계,매우 만족,약간 만족,보통,약간 불만족,매우 불만족,계,...,약간 만족,보통,약간 불만족,매우 불만족,계,매우 만족,약간 만족,보통,약간 불만족,매우 불만족
1,전국,전체,계,100,5.5,18.1,48.8,20.3,7.3,100,...,24.2,43.1,18.1,4.8,100,11.9,30.3,43.3,11.5,3
2,NaN,성별,남자,100,5.9,17.9,49.3,19.6,7.3,100,...,23.6,42.8,18.2,5.3,100,12.4,30.1,43,11.3,3.3
3,NaN,NaN,여자,100,5.2,18.2,48.3,21,7.2,100,...,24.8,43.4,18.1,4.3,100,11.5,30.5,43.6,11.8,2.7
4,서울특별시,전체,계,100,6.3,20.4,48.8,17.1,7.4,100,...,24.8,42.3,18.1,5.5,100,11.4,30.5,43.3,11.8,3.1
5,NaN,성별,남자,100,6.2,19.8,50,16.6,7.3,100,...,23.5,42,19,6,100,11.4,29.9,43.9,11.4,3.4
6,NaN,NaN,여자,100,6.3,21,47.6,17.6,7.5,100,...,26,42.6,17.3,5,100,11.4,30.9,42.8,12.1,2.8
7,부산광역시,전체,계,100,6.4,16.3,46,22.8,8.5,100,...,24.3,46.4,16.6,5.9,100,10.2,30.3,44.2,12.3,3
8,NaN,성별,남자,100,6.7,16.2,46.3,21.7,9.1,100,...,23.4,46.6,16.5,6.5,100,10.7,29.3,44.3,11.9,3.7
9,NaN,NaN,여자,100,6.1,16.3,45.7,23.9,8,100,...,25.1,46.3,16.7,5.3,100,9.7,31.3,44,12.7,2.3
10,대구광역시,전체,계,100,3.2,15.2,50.9,23.7,7.1,100,...,21.6,46,19.6,3.5,100,11.2,26.4,45.2,14.2,3.1
11,NaN,성별,남자,100,3.4,13.8,52.2,23.6,7,100,...,21.5,45.6,20.2,3.8,100,11.5,25.7,45.2,14,3.6
12,NaN,NaN,여자,100,3,16.4,49.6,23.9,7.1,100,...,21.6,46.3,19,3.1,100,10.8,27,45.2,14.4,2.5
13,인천광역시,전체,계,100,5.1,16.6,47,22.9,8.4,100,...,20.8,45.9,17.3,5.7,100,12.6,27.2,46.2,10.4,3.5
14,NaN,성별,남자,100,5.2,16.4,47.8,21.4,9.2,100,...,19.7,45.3,17.8,6.1,100,12.9,25.5,47.4,10.6,3.6
15,NaN,NaN,여자,100,5,16.8,46.3,24.2,7.6,100,...,21.8,46.5,16.8,5.4,100,12.3,28.9,45.1,10.3,3.4
16,광주광역시,전체,계,100,3.9,17.1,51.3,21.5,6.2,100,...,27.8,42.5,15.3,4.2,100,11.4,31.6,44.2,10.2,2.5
17,NaN,성별,남자,100,3.9,17.9,51.2,21,6,100,...,27.8,39.5,15.7,5.5,100,11.7,30.2,45.7,9.6,2.7
18,NaN,NaN,여자,100,3.9,16.4,51.4,22,6.4,100,...,27.8,45.4,14.8,3,100,11.2,33,42.8,10.8,2.2
19,대전광역시,전체,계,100,6,18.4,47.5,21.5,6.7,100,...,30.2,38.7,17.4,4.2,100,14.6,34.4,39.2,9.5,2.3
20,NaN,성별,남자,100,5.8,17.3,49.2,20.6,7,100,...,30.4,39.8,17.4,4.8,100,14.9,34.1,37.6,10.4,3.0
21,NaN,NaN,여자,100,6.1,19.4,45.8,22.3,6.4,100,...,30,37.7,17.3,3.6,100,14.3,34.7,40.7,8.6,1.6
22,울산광역시,전체,계,100,5.6,17.1,51.8,19.1,6.4,100,...,23.3,39.6,18.3,5.6,100,11,30.4,41.4,14,3.2
23,NaN,성별,남자,100,5.6,16.4,52.3,19.2,6.6,100,...,23.9,38.4,19.7,6,100,9.8,34.6,38.2,13.9,3.5
24,NaN,NaN,여자,100,5.7,17.8,51.3,19,6.2,100,...,22.6,40.8,16.7,5.3,100,12.3,25.8,44.8,14.1,3
25,세종특별자치시,전체,계,-,-,-,-,-,-,-,...,30.1,34.8,15,4.1,100,15.9,37.4,35.1,9.3,2.2
26,NaN,성별,남자,-,-,-,-,-,-,-,...,27.7,36,14.2,4.9,100,16.7,36.1,35.9,9,2.2
27,NaN,NaN,여자,-,-,-,-,-,-,-,...,32.5,33.5,15.9,3.3,100,15.2,38.6,34.3,9.7,2.2
28,경기도,전체,계,100,5.9,18.9,48.4,18.9,8,100,...,23.3,41,20.5,5.2,100,11.8,29.5,43.1,12.3,3.3
29,NaN,성별,남자,100,6.6,18.4,48.5,18.7,7.8,100,...,22.7,41.1,20.4,5.5,100,12.2,29.2,43.1,11.7,3.7
30,NaN,NaN,여자,100,5.2,19.4,48.2,19.1,8.1,100,...,23.9,41,20.6,4.9,100,11.5,29.7,43.1,12.9,2.8
31,강원특별자치도,전체,계,100,5.6,15.8,50.2,20.7,7.7,100,...,25.3,43.6,15,4,100,14.1,33,40.3,10.7,1.8
32,NaN,성별,남자,100,5.6,18,50.4,18.1,7.9,100,...,23.4,43.8,15,4.1,100,15.7,33.2,39.1,10.4,1.6
33,NaN,NaN,여자,100,5.7,13.7,50,23.3,7.4,100,...,27.2,43.3,14.9,3.8,100,12.5,32.9,41.5,11.1,2
34,충청북도,전체,계,100,4.9,16.5,49.3,22.3,7,100,...,24.5,46.2,14.8,3.4,100,13.5,31.8,39.9,11.6,3.2
35,NaN,성별,남자,100,4.7,16.1,50.3,23.1,5.8,100,...,24.9,46.5,13.5,3.7,100,13.3,30.8,41.1,11.2,3.6
36,NaN,NaN,여자,100,5.1,17,48.3,21.5,8.1,100,...,24.1,46,16.3,3.1,100,13.6,32.8,38.8,12.1,2.7
37,충청남도,전체,계,100,5.6,19.4,46.4,23.3,5.4,100,...,27.8,41.7,15.3,2.8,100,15.1,30,43.3,9.4,2.3
38,NaN,성별,남자,100,7,20.2,45.9,22.5,4.4,100,...,28.7,39.4,14.7,3.2,100,17,29.2,43.1,8.3,2.3
39,NaN,NaN,여자,100,4.1,18.7,46.9,24,6.3,100,...,26.8,44.1,15.9,2.4,100,13,30.8,43.4,10.5,2.2
40,전북특별자치도,전체,계,100,4.6,18,47.9,22.7,6.7,100,...,27.7,42.9,15.7,3.2,100,11.8,35.3,37.5,11.4,3.9
41,NaN,성별,남자,100,5,17.7,48.8,20.7,7.7,100,...,28.8,41.5,14.9,4.3,100,12.6,35,36.7,11.7,4
42,NaN,NaN,여자,100,4.3,18.3,47,24.6,5.7,100,...,26.6,44.2,16.5,2.2,100,11.1,35.7,38.2,11.1,3.9
43,전라남도,전체,계,100,5.4,15.9,53.8,19.8,5.1,100,...,25.9,44.3,14.6,3.5,100,13.5,28.5,46.7,9.1,2.2
44,NaN,성별,남자,100,6.4,17.4,51.8,19.7,4.8,100,...,25.2,43.4,14.5,4.4,100,15,28.1,44.1,10.9,1.9
45,NaN,NaN,여자,100,4.5,14.5,55.6,19.9,5.4,100,...,26.7,45.2,14.8,2.7,100,12,28.8,49.4,7.3,2.5
46,경상북도,전체,계,100,4.1,17.1,50.2,21.8,6.8,100,...,19.8,46.9,20.8,4.8,100,10.2,27.9,47.1,12,2.7
47,NaN,성별,남자,100,5.2,17.7,51.4,18.9,6.9,100,...,19,47.6,19.7,5.5,100,10.7,30.5,44.3,12.1,2.4
48,NaN,NaN,여자,100,3.1,16.6,49,24.7,6.7,100,...,20.6,46.2,21.9,4.1,100,9.8,25.3,50,12,3
49,경상남도,전체,계,100,5.4,16,49.6,22.3,6.6,100,...,24.1,45.4,18,4.2,100,10.7,33.7,43.6,9.7,2.4
50,NaN,성별,남자,100,5.2,16.5,50,21.1,7.1,100,...,23,45.2,17.9,5.5,100,11.3,34.8,42,9.5,2.5
51,NaN,NaN,여자,100,5.6,15.5,49.3,23.5,6.1,100,...,25.2,45.6,18.1,3,100,10.2,32.5,45.1,10,2.3
52,제주특별자치도,전체,계,100,5.3,20.7,49.6,20.3,4.1,100,...,24.8,41.7,15.8,4,100,13.1,31.6,42.9,9,3.3
53,NaN,성별,남자,100,5.8,21.3,47.4,20.9,4.6,100,...,24.1,42.4,14.4,4.8,100,14,31.7,40.4,10.2,3.7
54,NaN,NaN,여자,100,4.8,20.1,51.7,19.8,3.6,100,...,25.5,41,17.1,3.3,100,12.3,31.5,45.4,7.9,2.9

In [ ]:
culture_data.head(7, )

,행정구역별(1),특성별(1),특성별(2),2011,2011.1,2011.2,2011.3,2011.4,2011.5,2011.6,...,2023.11,2023.12,2023.13,2023.14,2023.15,2023.16,2023.17,2023.18,2023.19,2023.20
0,행정구역별(1),특성별(1),특성별(2),계 (%),관람함 (%),관람횟수(평균) (회),- 음악·연주회·콘서트 (%),· 관람 횟수(평균) (회),- 연극·마당극·뮤지컬 (%),· 관람 횟수(평균) (회),...,- 박물관 (%),· 관람 횟수(평균) (회),- 미술관 (%),· 관람 횟수(평균) (회),- 문학행사 (회),· 관람 횟수(평균) (%),- 스포츠 경기 (%),· 관람 횟수(평균) (회),- 기타 (%),· 관람 횟수(평균) (회)
1,전국,전체,계,100,58.6,8.4,25.2,2.5,25,2.3,...,25.1,2.4,23.2,2.3,8.1,2,27.3,4.4,0.6,4.8
2,NaN,성별,남자,100,58,8.2,21.4,2.5,19.6,2.1,...,22,2.4,17.1,2.2,6.4,2.1,37.3,4.7,0.6,6.1
3,NaN,NaN,여자,100,59.2,8.7,28.7,2.6,30.2,2.4,...,28.1,2.4,29,2.4,9.6,2,17.9,3.7,0.5,3.2
4,서울특별시,전체,계,100,67,9.7,29.8,2.6,34.9,2.5,...,27.8,2.7,28.1,2.5,7.7,1.9,25.9,4.4,0.2,4.5
5,NaN,성별,남자,100,65.7,9.3,25.3,2.6,27.3,2.3,...,24.6,2.5,19,2.3,5.8,2,35.9,5,0.2,6.4
6,NaN,NaN,여자,100,68.3,10,33.9,2.6,41.9,2.7,...,30.5,2.9,35.9,2.7,9.3,1.9,17.4,3.2,0.3,3.4

In [ ]:
life_data.head(7, )

,행정구역별(1),특성별(1),특성별(2),2011,2011.1,2011.2,2011.3,2011.4,2011.5,2013,...,2021.2,2021.3,2021.4,2021.5,2023,2023.1,2023.2,2023.3,2023.4,2023.5
0,행정구역별(1),특성별(1),특성별(2),계,매우 만족,약간 만족,보통,약간 불만족,매우 불만족,계,...,약간 만족,보통,약간 불만족,매우 불만족,계,매우 만족,약간 만족,보통,약간 불만족,매우 불만족
1,전국,전체,계,100,5.5,18.1,48.8,20.3,7.3,100,...,24.2,43.1,18.1,4.8,100,11.9,30.3,43.3,11.5,3
2,NaN,성별,남자,100,5.9,17.9,49.3,19.6,7.3,100,...,23.6,42.8,18.2,5.3,100,12.4,30.1,43,11.3,3.3
3,NaN,NaN,여자,100,5.2,18.2,48.3,21,7.2,100,...,24.8,43.4,18.1,4.3,100,11.5,30.5,43.6,11.8,2.7
4,서울특별시,전체,계,100,6.3,20.4,48.8,17.1,7.4,100,...,24.8,42.3,18.1,5.5,100,11.4,30.5,43.3,11.8,3.1
5,NaN,성별,남자,100,6.2,19.8,50,16.6,7.3,100,...,23.5,42,19,6,100,11.4,29.9,43.9,11.4,3.4
6,NaN,NaN,여자,100,6.3,21,47.6,17.6,7.5,100,...,26,42.6,17.3,5,100,11.4,30.9,42.8,12.1,2.8

In [ ]:
culture_data.describe().T

         count unique       top freq
행정구역별(1)    19     19  행정구역별(1)    1
특성별(1)      37      3        전체   18
특성별(2)      55      4         계   18
2011        55      3       100   51
2011.1      55     49         -    3
...        ...    ...       ...  ...
2023.16     55     18         2   10
2023.17   55.0   49.0      18.6  2.0
2023.18   55.0   28.0       4.3  9.0
2023.19     55     17       0.5    9
2023.20     55     35         1    9

[138 rows x 4 columns]

In [ ]:
life_data.describe().T

         count unique       top freq
행정구역별(1)    19     19  행정구역별(1)    1
특성별(1)      37      3        전체   18
특성별(2)      55      4         계   18
2011        55      3       100   51
2011.1    55.0   32.0       5.6  6.0
2011.2    55.0   39.0      16.4  4.0
2011.3    55.0   38.0      48.8  3.0
2011.4    55.0   41.0      21.5  3.0
2011.5    55.0   36.0       7.3  3.0
2013        55      3       100   51
2013.1    55.0   37.0      10.9  4.0
2013.2    55.0   41.0      23.9  3.0
2013.3    55.0   41.0      45.9  4.0
2013.4    55.0   37.0      17.2  3.0
2013.5    55.0   27.0       4.1  6.0
2015        55      2       100   54
2015.1    55.0   38.0      10.2  4.0
2015.2    55.0   41.0      22.8  3.0
2015.3      55     48        51    2
2015.4    55.0   33.0      13.5  5.0
2015.5    55.0   27.0       3.3  6.0
2017        55      2       100   54
2017.1    55.0   36.0       6.7  4.0
2017.2      55     45        23    4
2017.3    55.0   44.0      49.8  3.0
2017.4    55.0   43.0      18.9  3.0
2017.5    55.0   36.0       4.1  5.0
2019        55      2       100   54
2019.1    55.0   45.0      14.1  3.0
2019.2    55.0   37.0      23.8  4.0
2019.3    55.0   48.0      44.2  2.0
2019.4    55.0   34.0      12.8  4.0
2019.5    55.0   34.0       3.4  5.0
2021        55      2       100   54
2021.1    55.0   44.0      10.5  4.0
2021.2    55.0   42.0      27.8  4.0
2021.3      55     44        41    3
2021.4    55.0   37.0      18.1  4.0
2021.5    55.0   32.0       5.5  5.0
2023        55      2       100   54
2023.1    55.0   39.0      11.4  4.0
2023.2    55.0   48.0      30.5  3.0
2023.3    55.0   42.0      43.1  4.0
2023.4    55.0   40.0      12.1  3.0
2023.5    55.0   25.0       2.3  5.0

In [ ]:
culture_data.columns

Index(['행정구역별(1)', '특성별(1)', '특성별(2)', '2011', '2011.1', '2011.2', '2011.3',
       '2011.4', '2011.5', '2011.6',
       ...
       '2023.11', '2023.12', '2023.13', '2023.14', '2023.15', '2023.16',
       '2023.17', '2023.18', '2023.19', '2023.20'],
      dtype='object', length=138)

In [ ]:
life_data.columns

Index(['행정구역별(1)', '특성별(1)', '특성별(2)', '2011', '2011.1', '2011.2', '2011.3',
       '2011.4', '2011.5', '2013', '2013.1', '2013.2', '2013.3', '2013.4',
       '2013.5', '2015', '2015.1', '2015.2', '2015.3', '2015.4', '2015.5',
       '2017', '2017.1', '2017.2', '2017.3', '2017.4', '2017.5', '2019',
       '2019.1', '2019.2', '2019.3', '2019.4', '2019.5', '2021', '2021.1',
       '2021.2', '2021.3', '2021.4', '2021.5', '2023', '2023.1', '2023.2',
       '2023.3', '2023.4', '2023.5'],
      dtype='object')

In [ ]:
#문화예술 데이터 정보
print("데이터 크기:", culture_data.shape)
print("\n데이터 정보:")
culture_data.info()

데이터 크기: (55, 138)

데이터 정보:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Columns: 138 entries, 행정구역별(1) to 2023.20
dtypes: object(138)
memory usage: 59.4+ KB

In [ ]:
#삶의 만족도 데이터 정보
print("데이터 크기:", life_data.shape)
print("\n데이터 정보:")
life_data.info()

데이터 크기: (55, 45)

데이터 정보:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 45 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   행정구역별(1)  19 non-null     object
 1   특성별(1)    37 non-null     object
 2   특성별(2)    55 non-null     object
 3   2011      55 non-null     object
 4   2011.1    55 non-null     object
 5   2011.2    55 non-null     object
 6   2011.3    55 non-null     object
 7   2011.4    55 non-null     object
 8   2011.5    55 non-null     object
 9   2013      55 non-null     object
 10  2013.1    55 non-null     object
 11  2013.2    55 non-null     object
 12  2013.3    55 non-null     object
 13  2013.4    55 non-null     object
 14  2013.5    55 non-null     object
 15  2015      55 non-null     object
 16  2015.1    55 non-null     object
 17  2015.2    55 non-null     object
 18  2015.3    55 non-null     object
 19  2015.4    55 non-null     object
 20  2015.5    55 non-null     object
 21  2017      55 non-null     object
 22  2017.1    55 non-null     object
 23  2017.2    55 non-null     object
 24  2017.3    55 non-null     object
 25  2017.4    55 non-null     object
 26  2017.5    55 non-null     object
 27  2019      55 non-null     object
 28  2019.1    55 non-null     object
 29  2019.2    55 non-null     object
 30  2019.3    55 non-null     object
 31  2019.4    55 non-null     object
 32  2019.5    55 non-null     object
 33  2021      55 non-null     object
 34  2021.1    55 non-null     object
 35  2021.2    55 non-null     object
 36  2021.3    55 non-null     object
 37  2021.4    55 non-null     object
 38  2021.5    55 non-null     object
 39  2023      55 non-null     object
 40  2023.1    55 non-null     object
 41  2023.2    55 non-null     object
 42  2023.3    55 non-null     object
 43  2023.4    55 non-null     object
 44  2023.5    55 non-null     object
dtypes: object(45)
memory usage: 19.5+ KB


**데이터 전처리**

---